openapi: 3.0.0
info:
  title: Sample API
  description: test description
  version: 1.0.0

servers:
  - url: http://api.example.com/v1
    description: description
  - url: htts://api.test.example.com/va
    description: description 1

paths:
  /users:
    get:
      summary: Return all users.
      description: test desc
      responses: 
        '200':
          description: json array[]
          content: 
            application/json:
              schema:
                type: array
                items:
                  type: string
